# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
  record_events:
    default: true
    description: Should charm record all events it receives
    type: boolean
  consumes:
    default: '{"mongodb": ">4.0.0"}'
    description: Type and version of database required by this charm
    type: string
